# Generated by Django 5.1.2 on 2024-12-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_optimus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ouvidoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DENUNCIA', 'Denúncia'), ('SUGESTAO', 'Sugestão'), ('ELOGIO', 'Elogio'), ('OUTRO', 'Outro')], max_length=10)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('cidadao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_optimus.cidadao')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_optimus.servidor')),
            ],
        ),
    ]
