# Generated by Django 5.1.2 on 2024-11-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_feed', '0002_noticia_data_publicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionalidade',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='funcionalidade',
            name='url',
        ),
        migrations.AddField(
            model_name='funcionalidade',
            name='rota',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funcionalidade',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
