# Generated by Django 5.1.2 on 2024-11-02 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_feed', '0003_remove_funcionalidade_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='app_home_feed.categoria'),
            preserve_default=False,
        ),
    ]
