# Generated by Django 5.1.2 on 2024-11-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_feed', '0005_rename_embed_url_video_url_video_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkrapido',
            name='icone',
        ),
        migrations.RemoveField(
            model_name='linkrapido',
            name='nome',
        ),
        migrations.AddField(
            model_name='linkrapido',
            name='descricao',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkrapido',
            name='titulo',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
