# Generated by Django 5.1.2 on 2024-11-16 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home_feed', '0007_remove_video_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='banners/')),
            ],
        ),
        migrations.DeleteModel(
            name='Funcionalidade',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='linkrapido',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='video',
            name='descricao',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias_imagens/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='noticias_relacionadas',
            field=models.ManyToManyField(blank=True, to='app_home_feed.noticia'),
        ),
        migrations.AddField(
            model_name='imagembanner',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='app_home_feed.banner'),
        ),
    ]
