# Generated by Django 5.1.2 on 2024-12-08 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_optimus', '0003_alter_noticia_imagem'),
    ]

    operations = [
    ]
