# Generated by Django 5.1.2 on 2024-11-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_optimus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
