# Generated by Django 5.1.2 on 2024-11-26 05:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_optimus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('perfil', models.CharField(choices=[('cidadao', 'Cidadão'), ('servidor', 'Servidor')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('id_cidadao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cidadao', serialize=False, to='app_optimus.usuario')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Outro', 'Outro')], max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id_servidor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='servidor', serialize=False, to='app_optimus.usuario')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saude',
            fields=[
                ('id_saude', models.AutoField(primary_key=True, serialize=False)),
                ('num_cartao_sus', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('necessidades_especiais', models.BooleanField(default=False)),
                ('cidadao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saude', to='app_optimus.cidadao')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='app_optimus.cidadao')),
            ],
        ),
        migrations.CreateModel(
            name='Educacao',
            fields=[
                ('id_educacao', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_educacional', models.CharField(choices=[('Fundamental', 'Fundamental'), ('Medio', 'Médio'), ('Superior', 'Superior'), ('Outro', 'Outro')], max_length=20)),
                ('instituicao', models.CharField(blank=True, max_length=255, null=True)),
                ('cidadao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='educacao', to='app_optimus.cidadao')),
            ],
        ),
    ]
