# Generated by Django 5.1.2 on 2024-12-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_optimus', '0002_ouvidoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
