# Generated by Django 5.1.2 on 2024-12-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_optimus', '0003_alter_noticia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('servidor', 'Servidor'), ('cidadao', 'Cidadão'), ('admin', 'Administrador')], default='cidadao', max_length=50),
        ),
    ]
